python train_pseudo.py \
    --device cuda \
    --model deeplabv3_mobilenet_v3_large \
    --target greenhouse \
    --batch-size 32 \
    --epoch 30 \
    --lr 0.0009 \
    --label-update-epoch 10 \
    --save-path /tmp/runs/domain_gap/ \
    --scheduler cyclic \
    --is-hard true \
    --conf-thresh 0.9 \
    --ignore-index 3 